category/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('', views.category, name='category'),
    path('<skill_selected>', views.show, name='category'),
]


homepage/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('search', views.search, name='search'),
    path('chat', views.chat, name='chat')
   
]


skillworm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls')),
    path('account/', include('userentry.urls')),
    path('category/', include('category.urls')),
    path('admin/', admin.site.urls)
    
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userentry/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
]

accounts/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.
class UserType(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    teacher = models.BooleanField(default=False)
    student = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class UserData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default="")
    address = models.TextField()
    phone_number = models.CharField(max_length=10, validators=[RegexValidator(r'^\d[0123456789]{9}$')])
    city_ch = (
        ('Mumbai','Mumbai'),
        ('Delhi','Delhi'),
        ('Banglore','Banglore'),
    )
    city = models.CharField(max_length= 25 ,choices=city_ch, default='none')
    pincode = models.CharField(max_length=6, default="",validators=[RegexValidator(r'^\d[0123456789]{5}$')])
    id_proof = models.ImageField(upload_to='images/',default="")
    show_id = models.IntegerField(unique=True, null=False,default=1)
    decr = models.TextField(default='')


    def __str_(self):
        return self.user.username

class TutorCourse(models.Model):
    user = models.ForeignKey(User, related_name='tutorcor', on_delete=models.CASCADE)
    course = models.CharField(max_length=50)

class course(models.Model):
    student = models.ManyToManyField(User, blank= True, related_name='enrolled_students')
    tutor = models.ManyToManyField(User,  blank= True, related_name='Course_Tutors')
    cr_id = models.ManyToManyField(TutorCourse,  blank= True,related_name='Course')

class Review(models.Model):
   user = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
   review = models.TextField()
   rating = models.CharField(max_length=1)

class ReviewInline(admin.StackedInline):
    model = Review

class UserAdmin(admin.ModelAdmin):
    inlines = [
        ReviewInline,
    ]


    

category/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField(max_length=100, unique=True)
    category_info = models.TextField()

    def __str__(self):
        return self.category_name


class Skill(models.Model):
    skill_name = models.CharField(max_length=100, unique=True)
    skill_url = models.SlugField(max_length=100, null=True, blank=True)
    img = models.ImageField(upload_to='pictures')
    skill_info = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.skill_name

searchresult/models.py
from django.db import models

# Create your models here.

userentry/models.py
from django.db import models

# Create your models here.

accounts/views.py
from pyexpat.errors import messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.core.mail import send_mail
from userentry import views
from .models import UserType


# Create your views here.

def login(request):
    email = request.POST['email']
    password = request.POST['password']

    user = auth.authenticate(username=email, password=password)

    if user is not None:
        auth.login(request, user)
        return 3
    else:
        return 4


def logout(request):
    auth.logout(request)


def register(request):
    first_name = ''
    last_name = ''
    if request.method == 'POST':
        name = request.POST['name']
        if not name.isalpha:
            if ' ' in name:
                name = name.split()
                first_name = name[0]
                last_name = name[1]
        else:
            first_name = name
        username = request.POST['email']
        password = request.POST['password']
        email = request.POST['email']
        type_user = request.POST['type']

        if password == password:
            if User.objects.filter(username=email).exists():
                print('Username taken')
                return 1
            else:
                user = User.objects.create_user(username=username, password=password, email=email,
                                                first_name=first_name, last_name=last_name)
                user.save()
                if type_user == 'Student':
                    v1 = UserType(user=user, student=True)
                    v1.save()
                    print('Student')
                elif type_user == 'Teacher':
                    v1 = UserType(user=user, teacher=True)
                    v1.save()
                    print('Teacher')
                print('user created')
                return 0

category/views.py
from django.shortcuts import render
from homepage.models import Category, Skill


# Create your views here.

def category(request):
    skill_list = Skill.objects.all()
    category_list = Category.objects.all()
    params = {'categories': category_list}
    return render(request, 'categorypage.html', params)


def show(request, skill_selected):
    return render(request, 'searchresult.html')

homepage/views.py
from django.shortcuts import render
from .models import Skill
import random
from django.contrib.auth.decorators import login_required


def home(request):
    n = Skill.objects.count()
    r = []
    while len(r) < 4:
        rt = random.randrange(1, n + 1, 1)
        if rt not in r:
            r += [rt]
    print(r)
    skill_grp = Skill.objects.filter(id__in=r)
    print(skill_grp)

    return render(request, 'home.html', {'skills': skill_grp})


def search(request): 
    s =''      
    if request.method == 'GET': # this will be GET now      
        s =  request.GET.get('search').lower() # do some research what it does
        print(s)       
    skill_grp = Skill.objects.filter(skill_url__contains=s)
    print(skill_grp)
    
    return render(request, 'home.html',{'skills':skill_grp}) 


def chat(request): 
    return render(request, 'index.html') 

#cust_name = request.user.first_name
@login_required
def profile(request):  
    pass


searchresult/views.py
from django.shortcuts import render

# Create your views here.

userentry/views.py
from django.shortcuts import render, redirect
from accounts import views
from homepage import views as hviews
from pyexpat.errors import messages


def login(request):
    if request.method == 'POST':
        key = views.login(request)
        if key == 3:
            return redirect('/')
        elif key == 4:
            return render(request, 'loginregister.html', {'key': 0, 'alert': 0})
    else:
        return render(request, 'loginregister.html', {'key': 0})


def logout(request):
    views.logout(request)
    return redirect('/')
    #return render(request, 'home.html', {'alert': 1})


def register(request):
    if request.method == 'POST':
        key = views.register(request)
        if key == 0:
            return redirect('/account/login')
            #return render(request, "loginregister.html", {'key': key, 'alert': 2})
        else:
            return render(request, "loginregister.html", {'key': key, 'alert': 3})
    else:
        return render(request, "loginregister.html", {'key': 1})

templates/about.html
{% extends 'base.html' %}
{% block head %}
{% load static %} 
{% static 'images' as imagebase %}
{% endblock head %}
{% block body %}
<header class="bg-primary text-white">
    <div class="container text-center">
      <h1>Welcome to Scrolling Nav</h1>
      <p class="lead">A landing page template freshly redesigned for Bootstrap 4</p>
    </div>
  </header>

  <section id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>About this page</h2>
          <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled so you can use it as a boilerplate or starting point for you own landing page designs! This template features:</p>
          <ul>
            <li>Clickable nav links that smooth scroll to page sections</li>
            <li>Responsive behavior when clicking nav links perfect for a one page website</li>
            <li>Bootstrap's scrollspy feature which highlights which section of the page you're on in the navbar</li>
            <li>Minimal custom CSS so you are free to explore your own unique design options</li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section id="services" class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>Services we offer</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>Contact us</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
        </div>
      </div>
    </div>
  </section>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/navscroll.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% endblock body %}

templates/base.html
{% load static %} 
{% static 'images' as imagebase %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
{% block head %} 
{% endblock head%}
<link rel="stylesheet" href="{% static 'css/basestyle.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>SkillWorm</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container">
        <a class="navbar-brand " href="/home">
            <img src= "{% static 'images/logo.png' %}" height="30" class="d-inline-block align-top circle_img"  alt="I">
            SkillWorm
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Category
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Music</a>
                        <a class="dropdown-item" href="#">Something</a>
                        <a class="dropdown-item" href="/category">View all..</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Hi, {{ user.first_name }}!!
                        </a>
                    </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/account/logout">
                        Logout
                    </a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="/account/login">
                        Login
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/account/register">
                        Register
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>



{% block body %} 


{% endblock body %}

<script src="{% static 'js/navscroll.js' %}"></script> 
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="{% static 'js/script.js' %}"></script> 
</body>
</html>

templates/categorypage.html
{% extends 'base.html' %}
{% block head %}
{% load static %} 
{% static 'images' as imagebase %}
{% endblock head %}
{% block body %}
  <div class="container">
  <div class="row">
      <h1>Category</h1>
  </div>
      <div class="card-columns">
          {% for category in categories %}
              <!--<div class="col-md-4 my-3">-->
              <div class="card text-white bg-dark mb-3 ">
                  <div class="card-body">
                      <h5 class="card-title">{{ category.category_name }}</h5>
                      <p class="card-text">
                      <ul class="list-group">
                      {% for skill in category.skill_set.all %}
                          <a href="{{ skill.skill_url }}" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action list-group-item-dark">
                              {{skill.skill_name}}
                          <span class="badge badge-primary badge-pill">14</span>
                          </a>
                      {% endfor %}
                  </ul>
                      </p>
                  </div>
              </div>
              <!--</div>-->
          {% endfor %}
      </div>
  </div>
  


  <div class="card mb-3 mx-2 text-white bg-dark">
    <div class="row no-gutters">
      <div class="col-md-8 mx-3">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/navscroll.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% endblock body %}

templates/chat.html
{% extends 'base.html' %}
{% block head %}
{% load static %} 
{% static 'images' as imagebase %}
    <!-- Required meta tags -->
      <link rel="stylesheet" href="{% static 'css/homesection.css' %}">
      <link rel="stylesheet" href="{% static 'css/cardstyle.css' %}">
      <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
      
    <!-- Bootstrap CSS -->
    <script type="text/javascript" src="/static/js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
{% endblock head %}
{% block body %}
<div id="app" class="container top-padding">
    <div class="row">
        <div class="col-md-8 offset-md-2 col-sm-12">
            <div class="card col-md-6" v-for="message in messages" v-bind:class="{ 'user-message': message.user,  'chat-message': message.chat_bot, 'offset-md-6': message.chat_bot}">
                <div class="card-body">
                    [[message.text]]
                </div>
            </div>
        </div>

    </div>
    <div id="text-box" class="row top-padding">
        <div class="col-md-8 offset-md-2 col-sm-12">
            <textarea class="form-control" v-bind:placeholder="placeholder" v-model="input" v-bind:class="{ 'border-danger': send_blank}" v-on:change="check_content"></textarea>
            <i class="fas fa-arrow-circle-right send-btn" v-on:click="add_message"></i>
        </div>
    </div>
</div>

<script type="text/javascript" src="/static/js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
{% endblock body %}

templates/home.html
{% extends 'base.html' %}
{% block head %}
{% load static %} 
{% static 'images' as imagebase %}
    <!-- Required meta tags -->
      <link rel="stylesheet" href="{% static 'css/homesection.css' %}">
      <link rel="stylesheet" href="{% static 'css/cardstyle.css' %}">
      <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
    <!-- Bootstrap CSS -->
{% endblock head %}

{% block body %}
      <!-- Image and text -->
      <!-- NavBar and Page 1 -->
      <!-- NavBar  -->
          
      <section class="manscroll">
      <!-- alert for logout  -->
          {% if alert == 1 %}
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <strong>Logout Successful!</strong> See You Later.
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
          {% endif %}

          <!-- slider  -->
          <header>
              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  </ol>
                  <div class="carousel-inner" role="listbox">
                      <!-- Slide One -->
                      <div class="carousel-item active" class="d-flex justify-content-center" style="background-color: #FCFAFA">
                          <img src="{% static 'images/logo.png' %}" >
                          <div class="carousel-caption d-none d-md-block">
                              <h3 class="display-4 slide_text"></h3>
                              <p class="lead slide_text"></p>
                          </div>
                      </div>
                      <!-- Slide Two -->
                      <div class="carousel-item" class="d-flex justify-content-center" style="background-color: #FCFAFA">
                          <img src="{% static 'images/logo_tag.png' %}" >
                          <div class="carousel-caption d-none d-md-block" >
                              <h3 class="display-4 slide_text" ></h3>
                              <p class="lead slide_text"></p>
                          </div>
                      </div>
                      <!-- Slide Three -->
                      <div class="carousel-item " class="d-flex justify-content-center" style="background-color: #FCFAFA">
                          <img src="{% static 'images/logo.png' %}" >
                          <div class="carousel-caption d-none d-md-block">
                              <h3 class="display-4 slide_text"></h3>
                              <p class="lead slide_text"></p>
                          </div>
                      </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                  </a>
              </div>
          </header>
          <!-- Page Content 
        <div class="wrapper">
            <img class="h-5 d-inline-block" style="max-width: 100%;" src="https://i.ibb.co/9YNvVcN/photo-1522202176988-66273c2fd55f.jpg" class="img-fluid" alt="Responsive image" >
            <div class="col-xs-8" id="search-wrapper" >
                <form name="myform" method="GET" action="/search"> 

                <input  class="form-control input-lg" type="text" name='search' placeholder="Search for skills..">
            </form>
            </div>
          </div>
        -->

          <section class="py-5">
              <div class="container">
                  <h1 class="font-weight-light">Search</h1>
                  <!--<p class="lead">The background images for the slider are set directly in the HTML using inline CSS. The images in this snippet are from <a href="https://unsplash.com">Unsplash</a>!</p>-->
                  <div class="container" align ="center">
                    <form name="myform" method="GET" action="/search"> 
                      <input class="form-control input-lg" name='search' type="text" placeholder="Try..">
                      </form>
                  </div>
              </div>
          </section>
      </section>

     
      <section class="manscroll" >
      <div style="height: 8vh" class="d-flex align-items-center">
          <p>
              You should try these Skills.
          </p>
      </div>
      <div class="container">
      <div class="row">
          {% for s in skills %}
              <div class="col-md-3">
                  <article class="card card--{{ s.id }}">
                  <style type="text/css">
                              .card--{{ s.id }} .card__img,  .card--{{ s.id }} .card__img--hover{
                                  background-image: url('{{ s.img.url }}');
                              }
                          </style>
                      <div class="card__img">
                      </div>
                      <a href="/category/{{ s.skill_url }}" class="card_link">
                          <div class="card__img--hover"></div>
                      </a>
                      <div class="card__info">
                          <span class="card__category">{{s.category_name}}</span>
                          <h3 class="card__title">{{s.skill_name}}</h3>
                          <span class="card__by">Learn <a href="/category/{{ s.skill_url }}" class="card__author" title="author">Now</a></span>
                      </div>
                  </article>
              </div>
          {% endfor %}
      </div>
      </div>
      </section>
    
 <!-- Cards Page 2 
      <section class="manscroll" >
        <div style="height: 8vh" class="d-flex align-items-center">
            <p>
                You should try these Skills.
            </p>
        </div>
        
        <section class="cards " style="width: 100rem;">
            {% for s in skills %}
         
                    <article class="card card--{{ s.id }}">
                    <style type="text/css">
                                .card--{{ s.id }} .card__img,  .card--{{ s.id }} .card__img--hover{
                                    background-image: url('{{ s.img.url }}');
                                }
                            </style>
                        <div class="card__img">
                        </div>
                        <a href="#" class="card_link">
                            <div class="card__img--hover"></div>
                        </a>
                        <div class="card__info">
                            <span class="card__category">{{s.category_name}}</span>
                            <h3 class="card__title">{{s.skill_name}}</h3>
                            <span class="card__by">Learn <a href="#" class="card__author" title="author">Now</a></span>
                        </div>
                    </article>
            {% endfor %}
           
        </section>
        </section>



    -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
{% endblock body %}

templates/searchresult.html
{% extends 'base.html' %}
{% block head %}
{% load static %} 
{% static 'images' as imagebase %}
{% endblock head %}
{% block body %}
{% endblock body %}